# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  SDL2 = {
    pname = "SDL2";
    version = "release-2.32.0";
    src = fetchFromGitHub {
      owner = "libsdl-org";
      repo = "SDL";
      rev = "release-2.32.0";
      fetchSubmodules = false;
      sha256 = "sha256-BdyMlttrDwQMoz+bO6bfU3bh0xKnT8yQF6nb6OGRbHw=";
    };
  };
  SDL2_android = {
    pname = "SDL2_android";
    version = "release-2.0.18";
    src = fetchFromGitHub {
      owner = "libsdl-org";
      repo = "SDL";
      rev = "release-2.0.18";
      fetchSubmodules = false;
      sha256 = "sha256-R7MBR3QoXwR4Pg0YasSkwwyPTPOQLdgj6KJfyQKAKoc=";
    };
  };
  SDL2_mixer = {
    pname = "SDL2_mixer";
    version = "release-2.8.1";
    src = fetchFromGitHub {
      owner = "libsdl-org";
      repo = "SDL_mixer";
      rev = "release-2.8.1";
      fetchSubmodules = false;
      sha256 = "sha256-6HOTLwGi2oSQChwHE/oNHfZpcMh8xTuwNQSpKS01bwI=";
    };
  };
  dfwad = {
    pname = "dfwad";
    version = "6f1f5578319833eed6c2d14a4edb3acadef72bd6";
    src = fetchgit {
      url = "https://github.com/Doom2D/dfwad";
      rev = "6f1f5578319833eed6c2d14a4edb3acadef72bd6";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-ywsHzIW78U/C+jAsdSQ3WyGraA6t3E9BeDn14aUgCjk=";
    };
    date = "2025-01-14";
  };
  enet = {
    pname = "enet";
    version = "657eaf97d9d335917c58484a4a4b5e03838ebd8e";
    src = fetchgit {
      url = "https://github.com/lsalzman/enet";
      rev = "657eaf97d9d335917c58484a4a4b5e03838ebd8e";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-JIvasudVSQjWttg9fockmyJbGPrQe1hzsQRChpDzW8c=";
    };
    date = "2024-11-14";
  };
  fluidsynth = {
    pname = "fluidsynth";
    version = "209f46745a4cca9bf6367fae11920c7bce3b9681";
    src = fetchgit {
      url = "https://github.com/chirs241097/fluidsynth-sans-glib";
      rev = "209f46745a4cca9bf6367fae11920c7bce3b9681";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-NZ6Fe5Tj3BTQw6yEggJL4IfhX/MOuGtQLJfltJuUDMo=";
    };
    date = "2021-11-07";
  };
  fpc = {
    pname = "fpc";
    version = "0730e86c9db81917c48711b7f00c1dd503d1ac91";
    src = fetchgit {
      url = "https://gitlab.com/freepascal.org/fpc/source";
      rev = "0730e86c9db81917c48711b7f00c1dd503d1ac91";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-CZvBExE64inTQPwUW7NzzPXcWGRSbkyqHI5btTpkd/k=";
    };
    date = "2025-02-17";
  };
  game-music-emu = {
    pname = "game-music-emu";
    version = "0.6.3";
    src = fetchFromGitHub {
      owner = "libgme";
      repo = "game-music-emu";
      rev = "0.6.3";
      fetchSubmodules = false;
      sha256 = "sha256-XmPcFfKsEe07hH7f0xMs9hRJshOO/p58Zm9fYsmCCoA=";
    };
  };
  lazarus = {
    pname = "lazarus";
    version = "649f6ccbc83c3998a953f365fe5a985a2343411a";
    src = fetchgit {
      url = "https://gitlab.com/freepascal.org/lazarus/lazarus";
      rev = "649f6ccbc83c3998a953f365fe5a985a2343411a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-oOnsS1UoELipVODJIeER7bv9mcbu95k+C+IEP/maVdA=";
    };
    date = "2025-02-16";
  };
  libmodplug = {
    pname = "libmodplug";
    version = "d1b97ed0020bc620a059d3675d1854b40bd2608d";
    src = fetchgit {
      url = "https://github.com/Konstanty/libmodplug";
      rev = "d1b97ed0020bc620a059d3675d1854b40bd2608d";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-wBOAbCLUExdU+rg5NSghC8QXlMwsYBUkt2EsEvFKMug=";
    };
    date = "2022-01-31";
  };
  libmpg123 = {
    pname = "libmpg123";
    version = "6e06824f9bc16f4fc247a00c331b69c1f8148c4e";
    src = fetchgit {
      url = "https://github.com/madebr/mpg123";
      rev = "6e06824f9bc16f4fc247a00c331b69c1f8148c4e";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-JezLmOf+qsqrv5qtYDYe0Ta7ykyfYVq8cZ0iHL7jvgk=";
    };
    date = "2025-01-05";
  };
  libogg = {
    pname = "libogg";
    version = "v1.3.5";
    src = fetchFromGitHub {
      owner = "xiph";
      repo = "ogg";
      rev = "v1.3.5";
      fetchSubmodules = false;
      sha256 = "sha256-ync2np86Nje1R/g41VLhPhsld+yLZ40Pxv1wNzWCtss=";
    };
  };
  libopus = {
    pname = "libopus";
    version = "v1.5.2";
    src = fetchFromGitHub {
      owner = "xiph";
      repo = "opus";
      rev = "v1.5.2";
      fetchSubmodules = false;
      sha256 = "sha256-M1G7ypcfs7nJmXgkyoG96jT/CkgN5BOzy+DGO4LVCvA=";
    };
  };
  libvorbis = {
    pname = "libvorbis";
    version = "v1.3.7";
    src = fetchFromGitHub {
      owner = "xiph";
      repo = "vorbis";
      rev = "v1.3.7";
      fetchSubmodules = false;
      sha256 = "sha256-yCnbAxkbZN674F5HVd+DTmotvdtYnkJiO01B6foOiVY=";
    };
  };
  libxmp = {
    pname = "libxmp";
    version = "libxmp-4.6.1";
    src = fetchFromGitHub {
      owner = "libxmp";
      repo = "libxmp";
      rev = "libxmp-4.6.1";
      fetchSubmodules = false;
      sha256 = "sha256-jied4Rt1/Jh4OGFbQr4w1ALiXgsL3UYQEdJ2G/WRjqk=";
    };
  };
  miniupnpc = {
    pname = "miniupnpc";
    version = "miniupnpc_2_3_0";
    src = fetchFromGitHub {
      owner = "miniupnp";
      repo = "miniupnp";
      rev = "miniupnpc_2_3_0";
      fetchSubmodules = false;
      sha256 = "sha256-m26LlgvPm1uLi47r1W7x35yKFGX4gucZJHAaJlnrrQk=";
    };
  };
  openal = {
    pname = "openal";
    version = "1.24.2";
    src = fetchFromGitHub {
      owner = "kcat";
      repo = "openal-soft";
      rev = "1.24.2";
      fetchSubmodules = false;
      sha256 = "sha256-ECrIkxMACPsWehtJWwTmoYj6hGcsdxwVuTiQywG36Y8=";
    };
  };
  openal_android = {
    pname = "openal_android";
    version = "1.22.2";
    src = fetchFromGitHub {
      owner = "kcat";
      repo = "openal-soft";
      rev = "1.22.2";
      fetchSubmodules = false;
      sha256 = "sha256-MVM0qCZDWcO7/Hnco+0dBqzBLcWD279xjx0slxxlc4w=";
    };
  };
  opusfile = {
    pname = "opusfile";
    version = "9d718345ce03b2fad5d7d28e0bcd1cc69ab2b166";
    src = fetchgit {
      url = "https://github.com/xiph/opusfile";
      rev = "9d718345ce03b2fad5d7d28e0bcd1cc69ab2b166";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-7LvZMtYEkOR89QaQu2S+4xAz7d76CNMrc1ptYG7vUlM=";
    };
    date = "2022-11-22";
  };
  wavpack = {
    pname = "wavpack";
    version = "5.8.1";
    src = fetchFromGitHub {
      owner = "dbry";
      repo = "WavPack";
      rev = "5.8.1";
      fetchSubmodules = false;
      sha256 = "sha256-V9jRIuDpZYIBohJRouGr2TI32BZMXSNVfavqPl56YO0=";
    };
  };
}
