# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  SDL2 = {
    pname = "SDL2";
    version = "release-2.32.2";
    src = fetchFromGitHub {
      owner = "libsdl-org";
      repo = "SDL";
      rev = "release-2.32.2";
      fetchSubmodules = false;
      sha256 = "sha256-Gtg8G1tRouGZbes1KhsXpYbItpNHYqJCiQKW/L77b+U=";
    };
  };
  SDL2_android = {
    pname = "SDL2_android";
    version = "release-2.0.18";
    src = fetchFromGitHub {
      owner = "libsdl-org";
      repo = "SDL";
      rev = "release-2.0.18";
      fetchSubmodules = false;
      sha256 = "sha256-R7MBR3QoXwR4Pg0YasSkwwyPTPOQLdgj6KJfyQKAKoc=";
    };
  };
  SDL2_mixer = {
    pname = "SDL2_mixer";
    version = "release-2.8.1";
    src = fetchFromGitHub {
      owner = "libsdl-org";
      repo = "SDL_mixer";
      rev = "release-2.8.1";
      fetchSubmodules = false;
      sha256 = "sha256-6HOTLwGi2oSQChwHE/oNHfZpcMh8xTuwNQSpKS01bwI=";
    };
  };
  dfwad = {
    pname = "dfwad";
    version = "796f2fdebd21c46e741ef28cecb723b1c35398d5";
    src = fetchgit {
      url = "https://github.com/Doom2D/dfwad";
      rev = "796f2fdebd21c46e741ef28cecb723b1c35398d5";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-uCUVWF/GujuuzO/jBMqohUR75BBaSLYc3xF6UQO7iRY=";
    };
    date = "2025-03-05";
  };
  enet = {
    pname = "enet";
    version = "657eaf97d9d335917c58484a4a4b5e03838ebd8e";
    src = fetchgit {
      url = "https://github.com/lsalzman/enet";
      rev = "657eaf97d9d335917c58484a4a4b5e03838ebd8e";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [];
      sha256 = "sha256-JIvasudVSQjWttg9fockmyJbGPrQe1hzsQRChpDzW8c=";
    };
    date = "2024-11-14";
  };
  fluidsynth = {
    pname = "fluidsynth";
    version = "209f46745a4cca9bf6367fae11920c7bce3b9681";
    src = fetchgit {
      url = "https://github.com/chirs241097/fluidsynth-sans-glib";
      rev = "209f46745a4cca9bf6367fae11920c7bce3b9681";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [];
      sha256 = "sha256-NZ6Fe5Tj3BTQw6yEggJL4IfhX/MOuGtQLJfltJuUDMo=";
    };
    date = "2021-11-07";
  };
  fpc = {
    pname = "fpc";
    version = "d34d5c545944537cf458f5d388205cb88f3ee24a";
    src = fetchgit {
      url = "https://gitlab.com/freepascal.org/fpc/source";
      rev = "d34d5c545944537cf458f5d388205cb88f3ee24a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [];
      sha256 = "sha256-ggiI/2GxqhB5kN1nAMd2kghnDAEU3LxU7YG8vqeCgNA=";
    };
    date = "2025-03-04";
  };
  game-music-emu = {
    pname = "game-music-emu";
    version = "0.6.3";
    src = fetchFromGitHub {
      owner = "libgme";
      repo = "game-music-emu";
      rev = "0.6.3";
      fetchSubmodules = false;
      sha256 = "sha256-XmPcFfKsEe07hH7f0xMs9hRJshOO/p58Zm9fYsmCCoA=";
    };
  };
  lazarus = {
    pname = "lazarus";
    version = "847dee461c236f6460e66979f3eae77c12885a63";
    src = fetchgit {
      url = "https://gitlab.com/freepascal.org/lazarus/lazarus";
      rev = "847dee461c236f6460e66979f3eae77c12885a63";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [];
      sha256 = "sha256-oCFpVP2PXIDVV+geAcehtqCXisGg2uEw2FxoUakC4f4=";
    };
    date = "2025-03-05";
  };
  libmodplug = {
    pname = "libmodplug";
    version = "d1b97ed0020bc620a059d3675d1854b40bd2608d";
    src = fetchgit {
      url = "https://github.com/Konstanty/libmodplug";
      rev = "d1b97ed0020bc620a059d3675d1854b40bd2608d";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [];
      sha256 = "sha256-wBOAbCLUExdU+rg5NSghC8QXlMwsYBUkt2EsEvFKMug=";
    };
    date = "2022-01-31";
  };
  libmpg123 = {
    pname = "libmpg123";
    version = "6e06824f9bc16f4fc247a00c331b69c1f8148c4e";
    src = fetchgit {
      url = "https://github.com/madebr/mpg123";
      rev = "6e06824f9bc16f4fc247a00c331b69c1f8148c4e";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [];
      sha256 = "sha256-JezLmOf+qsqrv5qtYDYe0Ta7ykyfYVq8cZ0iHL7jvgk=";
    };
    date = "2025-01-05";
  };
  libogg = {
    pname = "libogg";
    version = "v1.3.5";
    src = fetchFromGitHub {
      owner = "xiph";
      repo = "ogg";
      rev = "v1.3.5";
      fetchSubmodules = false;
      sha256 = "sha256-ync2np86Nje1R/g41VLhPhsld+yLZ40Pxv1wNzWCtss=";
    };
  };
  libopus = {
    pname = "libopus";
    version = "v1.5.2";
    src = fetchFromGitHub {
      owner = "xiph";
      repo = "opus";
      rev = "v1.5.2";
      fetchSubmodules = false;
      sha256 = "sha256-M1G7ypcfs7nJmXgkyoG96jT/CkgN5BOzy+DGO4LVCvA=";
    };
  };
  libvorbis = {
    pname = "libvorbis";
    version = "v1.3.7";
    src = fetchFromGitHub {
      owner = "xiph";
      repo = "vorbis";
      rev = "v1.3.7";
      fetchSubmodules = false;
      sha256 = "sha256-yCnbAxkbZN674F5HVd+DTmotvdtYnkJiO01B6foOiVY=";
    };
  };
  libxmp = {
    pname = "libxmp";
    version = "libxmp-4.6.2";
    src = fetchFromGitHub {
      owner = "libxmp";
      repo = "libxmp";
      rev = "libxmp-4.6.2";
      fetchSubmodules = false;
      sha256 = "sha256-AfHathuBmF9OhtTyt8WabZKzFtnAkX1YeiYFF079z80=";
    };
  };
  miniupnpc = {
    pname = "miniupnpc";
    version = "miniupnpc_2_2_6";
    src = fetchFromGitHub {
      owner = "miniupnp";
      repo = "miniupnp";
      rev = "miniupnpc_2_2_6";
      fetchSubmodules = false;
      sha256 = "sha256-UropqH4YNR42R7L03ROx2j6Sq5RcqQ/64VYb2GcCkY8=";
    };
  };
  openal = {
    pname = "openal";
    version = "1.24.2";
    src = fetchFromGitHub {
      owner = "kcat";
      repo = "openal-soft";
      rev = "1.24.2";
      fetchSubmodules = false;
      sha256 = "sha256-ECrIkxMACPsWehtJWwTmoYj6hGcsdxwVuTiQywG36Y8=";
    };
  };
  openal_android = {
    pname = "openal_android";
    version = "1.22.2";
    src = fetchFromGitHub {
      owner = "kcat";
      repo = "openal-soft";
      rev = "1.22.2";
      fetchSubmodules = false;
      sha256 = "sha256-MVM0qCZDWcO7/Hnco+0dBqzBLcWD279xjx0slxxlc4w=";
    };
  };
  opusfile = {
    pname = "opusfile";
    version = "9d718345ce03b2fad5d7d28e0bcd1cc69ab2b166";
    src = fetchgit {
      url = "https://github.com/xiph/opusfile";
      rev = "9d718345ce03b2fad5d7d28e0bcd1cc69ab2b166";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [];
      sha256 = "sha256-7LvZMtYEkOR89QaQu2S+4xAz7d76CNMrc1ptYG7vUlM=";
    };
    date = "2022-11-22";
  };
  wavpack = {
    pname = "wavpack";
    version = "5.8.1";
    src = fetchFromGitHub {
      owner = "dbry";
      repo = "WavPack";
      rev = "5.8.1";
      fetchSubmodules = false;
      sha256 = "sha256-V9jRIuDpZYIBohJRouGr2TI32BZMXSNVfavqPl56YO0=";
    };
  };
}
