# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  SDL2 = {
    pname = "SDL2";
    version = "release-2.30.11";
    src = fetchFromGitHub {
      owner = "libsdl-org";
      repo = "SDL";
      rev = "release-2.30.11";
      fetchSubmodules = false;
      sha256 = "sha256-2NVZNqYhnAsljuF0BhBSJ5HmE9cS41gJep4Q3VxUGkY=";
    };
  };
  SDL2_mixer = {
    pname = "SDL2_mixer";
    version = "release-2.8.0";
    src = fetchFromGitHub {
      owner = "libsdl-org";
      repo = "SDL_mixer";
      rev = "release-2.8.0";
      fetchSubmodules = false;
      sha256 = "sha256-jLKawxnwP5dJglUhgHfWgmKh27i32Rr4LcJQdpXasco=";
    };
  };
  dfwad = {
    pname = "dfwad";
    version = "697d7d65441ee05841c2ea0fd6cb7c6bb544cfe9";
    src = fetchgit {
      url = "https://github.com/Doom2D/dfwad";
      rev = "697d7d65441ee05841c2ea0fd6cb7c6bb544cfe9";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [];
      sha256 = "sha256-2/Lhbg1HQVdVwxto8KjDYeGOoY9uVoIGWr+ubYexZ+Y=";
    };
    date = "2025-01-06";
  };
  enet = {
    pname = "enet";
    version = "657eaf97d9d335917c58484a4a4b5e03838ebd8e";
    src = fetchgit {
      url = "https://github.com/lsalzman/enet";
      rev = "657eaf97d9d335917c58484a4a4b5e03838ebd8e";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [];
      sha256 = "sha256-JIvasudVSQjWttg9fockmyJbGPrQe1hzsQRChpDzW8c=";
    };
    date = "2024-11-14";
  };
  fluidsynth = {
    pname = "fluidsynth";
    version = "c313f04b26b701b6766bcc42340e33c120a1b7cb";
    src = fetchgit {
      url = "https://github.com/DominusExult/fluidsynth-sans-glib.git";
      rev = "c313f04b26b701b6766bcc42340e33c120a1b7cb";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [];
      sha256 = "sha256-6b3aNBuT2B1bDSlTklJyjAhTjGZjcAQKTdtjvnFQKS0=";
    };
    date = "2025-01-01";
  };
  game-music-emu = {
    pname = "game-music-emu";
    version = "0.6.3";
    src = fetchFromGitHub {
      owner = "libgme";
      repo = "game-music-emu";
      rev = "0.6.3";
      fetchSubmodules = false;
      sha256 = "sha256-XmPcFfKsEe07hH7f0xMs9hRJshOO/p58Zm9fYsmCCoA=";
    };
  };
  libmodplug = {
    pname = "libmodplug";
    version = "d1b97ed0020bc620a059d3675d1854b40bd2608d";
    src = fetchgit {
      url = "https://github.com/Konstanty/libmodplug";
      rev = "d1b97ed0020bc620a059d3675d1854b40bd2608d";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [];
      sha256 = "sha256-wBOAbCLUExdU+rg5NSghC8QXlMwsYBUkt2EsEvFKMug=";
    };
    date = "2022-01-31";
  };
  libmpg123 = {
    pname = "libmpg123";
    version = "6e06824f9bc16f4fc247a00c331b69c1f8148c4e";
    src = fetchgit {
      url = "https://github.com/madebr/mpg123";
      rev = "6e06824f9bc16f4fc247a00c331b69c1f8148c4e";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [];
      sha256 = "sha256-JezLmOf+qsqrv5qtYDYe0Ta7ykyfYVq8cZ0iHL7jvgk=";
    };
    date = "2025-01-05";
  };
  libogg = {
    pname = "libogg";
    version = "v1.3.5";
    src = fetchFromGitHub {
      owner = "xiph";
      repo = "ogg";
      rev = "v1.3.5";
      fetchSubmodules = false;
      sha256 = "sha256-ync2np86Nje1R/g41VLhPhsld+yLZ40Pxv1wNzWCtss=";
    };
  };
  libopus = {
    pname = "libopus";
    version = "v1.5.2";
    src = fetchFromGitHub {
      owner = "xiph";
      repo = "opus";
      rev = "v1.5.2";
      fetchSubmodules = false;
      sha256 = "sha256-M1G7ypcfs7nJmXgkyoG96jT/CkgN5BOzy+DGO4LVCvA=";
    };
  };
  libvorbis = {
    pname = "libvorbis";
    version = "v1.3.7";
    src = fetchFromGitHub {
      owner = "xiph";
      repo = "vorbis";
      rev = "v1.3.7";
      fetchSubmodules = false;
      sha256 = "sha256-yCnbAxkbZN674F5HVd+DTmotvdtYnkJiO01B6foOiVY=";
    };
  };
  libxmp = {
    pname = "libxmp";
    version = "libxmp-4.6.1";
    src = fetchFromGitHub {
      owner = "libxmp";
      repo = "libxmp";
      rev = "libxmp-4.6.1";
      fetchSubmodules = false;
      sha256 = "sha256-jied4Rt1/Jh4OGFbQr4w1ALiXgsL3UYQEdJ2G/WRjqk=";
    };
  };
  openal = {
    pname = "openal";
    version = "1.24.1";
    src = fetchFromGitHub {
      owner = "kcat";
      repo = "openal-soft";
      rev = "1.24.1";
      fetchSubmodules = false;
      sha256 = "sha256-WDnvdU4eSQ0BVBeAB0LXCbZtbjo7/3hqi1g2HJieHIo=";
    };
  };
  opusfile = {
    pname = "opusfile";
    version = "9d718345ce03b2fad5d7d28e0bcd1cc69ab2b166";
    src = fetchgit {
      url = "https://github.com/xiph/opusfile";
      rev = "9d718345ce03b2fad5d7d28e0bcd1cc69ab2b166";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [];
      sha256 = "sha256-7LvZMtYEkOR89QaQu2S+4xAz7d76CNMrc1ptYG7vUlM=";
    };
    date = "2022-11-22";
  };
  wavpack = {
    pname = "wavpack";
    version = "5.7.0";
    src = fetchFromGitHub {
      owner = "dbry";
      repo = "WavPack";
      rev = "5.7.0";
      fetchSubmodules = false;
      sha256 = "sha256-vFZxg1mVqE7Kp38vEGA5V8m2tjqhssFsUZURixhlfk0=";
    };
  };
}
